models/Employees.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "employees".
 *
 * @property int $id
 * @property string $first_name
 * @property string $last_name
 * @property string $middel_name
 *
 * @property EmployeesFaculty[] $employeesFaculties
 */
class Employees extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'employees';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['first_name', 'last_name', 'middel_name'], 'string', 'max' => 250],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'first_name' => 'Фамилия',
            'last_name' => 'Имя',
            'middel_name' => 'Отчество',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmployeesFaculties()
    {
        return $this->hasMany(EmployeesFaculty::className(), ['employe_id' => 'id']);
    }
}

controllers/CommonConfController.php
<?php


namespace app\controllers;


use app\models\School;
use Yii;
use yii\web\Controller;

class CommonConfController extends Controller
{
    public function actionIndex()
    {
        $school = $this->findSchool(1);

        if ($school->load(Yii::$app->request->post()) && $school->save()) {
            $this->redirect(['index']);
        }

        return $this->render('index', ['school' => $school]);
    }

    /**
     * @param $id
     * @return School|null
     */
    private function findSchool($id)
    {
        return School::findOne($id);
        // TODO Not found exception
    }
}

controllers/EmployeesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Employees;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * EmployeesController implements the CRUD actions for Employees model.
 */
class EmployeesController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Employees models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Employees::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Employees model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Employees model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Employees();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Employees model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Employees model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Employees model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Employees the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Employees::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/SpecialtiesController.php
<?php

namespace app\controllers;

use app\models\Faculty;
use app\models\SpecialtyFacultyMap;
use Yii;
use app\models\Specialty;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SpecialtiesController implements the CRUD actions for Specialty model.
 */
class SpecialtiesController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Specialty models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Specialty::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Specialty model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Specialty();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $this->saveFaculties($model->id, Yii::$app->request->post('hours'));
            return $this->redirect(['index']);
        }

        return $this->render('create', [
            'model' => $model,
            'facultiesMaps' => $this->getSpecialtyFacultyMaps(),
            'faculties' => $this->getFaculties(),
        ]);
    }

    /**
     * Updates an existing Specialty model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $this->saveFaculties($model->id, Yii::$app->request->post('hours'));
            return $this->redirect(['index']);
        }

        return $this->render('update', [
            'model' => $model,
            'facultiesMaps' => $this->getSpecialtyFacultyMaps(),
            'faculties' => $this->getFaculties(),
        ]);
    }

    /**
     * Deletes an existing Specialty model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Specialty model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Specialty the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Specialty::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    private function getSpecialtyFacultyMaps()
    {
        return SpecialtyFacultyMap::find()->indexBy('faculty_id')->all();
    }

    private function getFaculties()
    {
        return Faculty::find()->all();
    }

    private function saveFaculties($specialtyId, $hours)
    {
        if (!$hours) {
            return;
        }

        SpecialtyFacultyMap::deleteAll();

        foreach ($hours as $faculty_id => $hour) {
            if (!$hours) {
                continue;
            }
            $map = new SpecialtyFacultyMap([
                'faculty_id' => $faculty_id,
                'specialty_id' => $specialtyId,
                'example_hour' => $hour,
            ]);
            $map->save();
        }


    }
}

views/employees/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Employees */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="employees-form">

    <?php $form = ActiveForm::begin(); ?>

    <div style="margin-left: 330px">
        <h4><?php
            if ($model->id) {
                echo $model->first_name . ' ' . $model->last_name . ' ' . $model->middel_name;
            }
            ?></h4>
        <div class="row">
            <div class="col-md-4">
                <?= $form->field($model, 'first_name')->textInput(['maxlength' => true]) ?>
            </div>
            <div class="col-md-4">
                <?= $form->field($model, 'last_name')->textInput(['maxlength' => true]) ?>
            </div>
            <div class="col-md-4">
                <?= $form->field($model, 'middel_name')->textInput(['maxlength' => true]) ?>
            </div>
            <div class="col-md-12">
                <?php
                $facultyEmp = \app\models\EmployeesFaculty::findAll(['employe_id' => $model->id]);
                ?>
                <table class="table table-bordered" id="facultTable" data-index="<?= count($facultyEmp) ?>">
                    <tr>
                        <td>#</td>
                        <td>Факультет</td>
                        <td>Количество часов</td>
                        <td></td>
                    </tr>
                    <?php
                    foreach ($facultyEmp as $index => $faculty) {
                        ?>
                        <tr>
                            <td><?= $index ?></td>
                            <td><?= $faculty->faculty->title_ru ?></td>
                            <td><?= $faculty->count_hour ?></td>
                            <td><i class="glyphicon glyphicon-remove"
                                   id="<?= $faculty->faculty->id ?>"></i></td>
                        </tr>
                        <?php
                    }
                    ?>
                </table>
            </div>
            <div class="col-md-4">
                Факультет:
                <select class="form-control" id="selected">
                    <?php
                    $facultyes = \app\models\Faculty::find()->all();
                    foreach ($facultyes as $faculty) {
                        echo '<option value="' . $faculty->id . '">' . $faculty->title_ru . '</option>';
                    }
                    ?>
                </select>
            </div>
            <div class="col-md-4">
                Количество часов:
                <input type="number" class="form-control" id="countHour">
            </div>
            <div class="col-md-4">
                <label></label>
                <a class="btn btn-success addFaculty form-control" data-employe="<?= $model->id ?>">Добавить</a>
            </div>
            <div class="col-md-12" style="display: none">
                <div class="text-center
" style="background: red; padding: 7px">
                    <h4 style="color: white">Произошла ошибка!</h4>
                    <p style="color: white">Необходимо создать сотрудника!</p>
                </div>
            </div>
        </div>
    </div>


    <div class="form-group  text-right" style="margin-top: 15px">
        <?php
        $btnText = 'Добавить';
        if ($model->id) {
            $btnText = 'Сохранить';
        }
        ?>
        <?= Html::submitButton($btnText, ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/employees/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Employees */

$this->title = 'Добавить сотрудника';
$this->params['breadcrumbs'][] = ['label' => 'Сотрудники', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="employees-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/employees/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Employees';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="employees-index">

    <ul class="nav nav-tabs">
        <li role="presentation"><?= Html::a('Основные', ['common-conf/index']) ?></li>
        <li role="presentation"><?= Html::a('Специальности', ['/specialties/index']) ?></li>
        <li role="presentation" class="active"><?= Html::a('Сотрудники', ['/employees/index']) ?></li>
    </ul>

    <br>

    <p>
        <?= Html::a('Добавить сотрудника', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'first_name',
            'last_name',
            'middel_name',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

views/employees/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Employees */

$this->title = 'Обновить информацию о сотруднике';
$this->params['breadcrumbs'][] = ['label' => 'Сотрудники', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="employees-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/employees/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Employees */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Сотрудники', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="employees-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'first_name',
            'last_name',
            'middel_name',
        ],
    ]) ?>

</div>